### ISSUE TITLE
rat according to isthisarat.com

### ISSUE THREAD

**Issue by dawidek2233** [TotallyAlexTFM/TFM-Hypixel-Skyblock#1]
Code Analysis
org/h2/jmx/DatabaseInfo.class
session id
Mentions session IDs, this might be bad or good

org/h2/expression/Function.class
SESSION_ID
Mentions session IDs, this might be bad or good

org/h2/table/MetaTable.class
SESSION_ID
Mentions session IDs, this might be bad or good

**Comment by seq47** [comment]
Quite literally the API's session ID, isthisarat.com is not exactly accurate for rat checking. It does catch basic ones though
